### ISSUE TITLE
lazy variants

### ISSUE THREAD

**Issue by expipiplus1** [jamesdbrock/replace-attoparsec#3]
Would it make sense to have lazy text and bytestring versions of the modules exposed here. ~~As far as I can tell it should just be adding `.Lazy` to some module imports and writing `takeCheat` for the text editor.~~ Not sure how much work this would entail

**Comment by jamesdbrock** [comment]
I think it would make sense, yes.

Clearly you've looked at the code and you can see what's going on there.

> ~As far as I can tell it should just be adding `.Lazy` to some module imports and writing `takeCheat` for the text editor.~

That's probably correct? But there may be surprises. If you make a PR for this which passes tests then I will gratefully merge it.

**Comment by jamesdbrock** [comment]
Done in #4
